# Generated by Django 4.1.2 on 2024-03-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='img',
        ),
    ]
