# Generated by Django 4.1.2 on 2024-03-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userpayment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
