# Generated by Django 4.1.2 on 2024-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userpayment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
